<?xml version="1.0"?>
<robot name="imarc" xmlns:xacro="http://www.ros.org/wiki/xacro">


<xacro:property name="namespace" value="imarc"/>

<!-- mass in kg, volume in m^3 123.225, -->
<xacro:property name="mass" value="12"/>
<xacro:property name="volume" value="0.274"/>

<xacro:property name="length" value="1.219"/>
<xacro:property name="width" value="0.737"/>
<xacro:property name="depth" value="0.3048"/>


<xacro:include filename="$(find imarc_description)/urdf/imarc.gazebo"/>

<!-- TODO: maybe calc center of buoyancy -->

	<link name="body">
		<visual name="body_visual">
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="${length} ${width} ${depth}"/>
			</geometry>
		</visual>

		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="${length} ${width} ${depth}"/>
			</geometry>
		</collision>

		<inertial>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<mass value="${mass}"/>
		<inertia ixx="${(width*width + depth*depth)*mass/12.0 }"  ixy="0"  ixz="0" iyy="${(length*length + depth*depth)*mass/12.0}" iyz="0" izz="${(length*length + depth*depth)*mass/12.0}"/>
		</inertial>
	</link>

  <joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0 0 ${depth*0.5}" rpy="0 0 0"/>
    <parent link="body"/>
    <child link="hokuyo_link"/>
  </joint>

	<!-- Hokuyo Laser -->
	<link name="hokuyo_link">
		<collision>
		  <origin xyz="0 0 0" rpy="0 0 0"/>
		  <geometry>
		    <box size="0.1 0.1 0.1"/>
		  </geometry>
		</collision>

		<visual>
		  <origin xyz="0 0 0" rpy="0 0 0"/>
		  <geometry>
		    <box size="0.1 0.1 0.1"/>
		  </geometry>
		</visual>

		<inertial>
		  <mass value="1e-5" />
		  <origin xyz="0 0 0" rpy="0 0 0"/>
		  <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
		</inertial>
	</link>

</robot>



